### ISSUE TITLE
Add tagging for Multiplayer types

### ISSUE THREAD

**Issue by Clusters** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#13]
Would it be possible to add tagging for Multiplayer types, like Local, LAN, etc.

This is currently the only possibility to filter for Couch-Coop and LAN party games.

**Comment by sharkusmanch** [comment]
Can you give an example of a game's page on PCGamingWiki with the data you'd like?

From what I can tell, only Singleplayer or Multiplayer is differentiated.

There's a `CooperativeModesImporter` extension developed by @darklinkpower that covers the coop portion using data from cooptimus - https://github.com/darklinkpower/PlayniteExtensionsCollection/tree/master/source/Generic/CooperativeModesImporter

**Comment by bverkron** [comment]
I would love this feature as well. I think what @Clusters means is more specific multiplayer information like whether it supports PvP. Co-optimus and that extension are really great but only provide info if the games supports co-op gameplay not PvP or other edge cases (like Hot Seat aka Pass & Play).

A use case for this info for me is deciding which Local (i.e. split screen) games to play with the kids. Sometimes we want to do something that involves working together (Co-op) and other times we want to battle it out (PvP).

One example of an entry with non co-op metadata is Ark: Survival Evolved. It supports the following kinds of multiplayer. So, `Local: Versus` would be split screen PvP effectively.

![image](https://user-images.githubusercontent.com/19174503/159146103-2e9d3d4f-892e-4cad-a9d0-d9692d6ab4b6.png)

![image](https://user-images.githubusercontent.com/19174503/159146240-3e86eb25-20d3-4c4e-80e9-b5c5c9f97f40.png)

**Comment by sharkusmanch** [comment]
Added in v0.5.0. Now adds features (only when natively supported) for `Local Multiplayer: Versus`, `Local Multiplayer: Co-op`, etc.

Will look at adding support for the `Hackable` rating in a future version (for this and other tags/features)

**Comment by sharkusmanch** [comment]
Added player counts to features in v0.5.1. Example for Gears 5:

<img width="280" alt="features" src="https://user-images.githubusercontent.com/9328629/159177027-c809ecbd-69cc-48ca-a650-1279462d88d6.PNG">

**Comment by bverkron** [comment]
Amazing, thank you so much!

**Comment by Clusters** [comment]
Thanks a lot! ☺
