### ISSUE TITLE
Add option to mark different types of tags

### ISSUE THREAD

**Issue by HerrKnarz** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#24]
Since there are different types of tags like engine, perspective, pacing etc. it would be great to have an option to add the type to the name of the tag - for example "[Perspective] First-person" or "[Engine] Unreal Engine 4". That way the tags can be sorted by type and are easier to grasp.

**Comment by sharkusmanch** [comment]
Added in v1.0.3
