### ISSUE TITLE
Multiplayer modes for some games are not detected

### ISSUE THREAD

**Issue by Clusters** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#34]
First of all, thank you so much for the work you're putting in! And also for the last two patches. They increased detection and now almost all my Couch-Gaming games are detected correctly. However and for a reason I can not reproduce, some games are not detected correctly.

To name some examples:
https://www.pcgamingwiki.com/wiki/Tumblestone
https://www.pcgamingwiki.com/wiki/Regular_Human_Basketball
https://www.pcgamingwiki.com/wiki/Tricky_Towers

What's the difference here in comparison to games which are detected correctly?

**Comment by sharkusmanch** [comment]
Thanks for reporting. The issue appears to be the `[citation needed]` marker in the infobox. The parser wasn't properly removing this, causing an exception.

Fixed in v1.1.2 - https://github.com/sharkusmanch/playnite-pcgamingwiki-metadata-provider/pull/35

**Comment by Clusters** [comment]
Sorry for my late response! Its working perfect!
Idk why it wasn't working for me when I tried to fix it with the same approach 😅
