### ISSUE TITLE
Feature-tags: Touchscreen/Controller optimised

### ISSUE THREAD

**Issue by forenta** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#38]
I use Playnite on my TV and Detachable - so I have set filters for each so that only supported games are displayed.
Unfortunately, unlike other metadata-addons, this one does not consider the tags from PCGW so far. It would be nice if this could be implemented.
Thanks for the work!

**Comment by sharkusmanch** [comment]
Can you provide an example PCGamingWiki page that has the data you're looking for?

**Comment by forenta** [comment]
https://www.pcgamingwiki.com/wiki/Cat_Lady_-_The_Card_Game#Input

**Comment by sharkusmanch** [comment]
Added in v1.1.4
