### ISSUE TITLE
Series names with a comma are split in two

### ISSUE THREAD

**Issue by Acru** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#54]
Came across this minor issue, but thought would report anyway, Series:Warhammer_40,000 was split into two different series at the comma when fetching metadata.

**Comment by sharkusmanch** [comment]
Thanks for reporting!

Do you know of any game pages that have multiple series listed? Want to make sure any changes I make here cover those as well

**Comment by sharkusmanch** [comment]
Fixed in 1.2.1

**Comment by Acru** [comment]
> Do you know of any game pages that have multiple series listed? Want to make sure any changes I make here cover those as well

Here are a couple useful test cases;
`Black Widow: Recharged` and `Centipede Recharged`, have two series listed, among other things in `Series:Atari Recharged`
`Series:Cook, Serve, Delicious!` has two commas in the series name~
