### ISSUE TITLE
Multiple Series get merged into one

### ISSUE THREAD

**Issue by Nanodunkel** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#58]
PCGW supports adding multiple Series to a game.
Sometimes? they get merged into one Series.

Most notably here is the Assassin's Creed Chronicles Series.
ACC China gets `Assassin's Creed Chronicles, Assassin's Creed` as a `series` tag(as one series)
while ACC Russia and India get no series assigned.
Though that might be related to #40 bc
China(`Assassin's Creed Chronicles China`) uses `'`
Russia(`Assassin’s Creed Chronicles Russia`) and India(`Assassin’s Creed Chronicles India`) use `’`

others are:
`Asteroids: Recharged` `series`=`Asteroids, Atari Recharged`
`Black Widow: Recharged` `series`=`Black Widow, Atari Recharged`
`Centipede Recharged` `series`=`Centipede, Atari Recharged`
`Discovery Tour: Ancient Greece by Ubisoft` `series`=`Discovery Tour, Assassin's Creed`

**Comment by sharkusmanch** [comment]
Fixed in v1.2.2
