### ISSUE TITLE
Ray Tracing feature not added for compatible games

### ISSUE THREAD

**Issue by yasathedog123** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#74]
the title kinda says everything,
since i would love to filter on RayTracing,
it doesn't seem to work even if the PCGamingWiki link shows it supports raytracing

**Comment by sharkusmanch** [comment]
Looks like ray tracing in the articles was renamed from `Ray tracing` to `Ray tracing (RT)`

**Comment by sharkusmanch** [comment]
Fixed in 1.2.3
