### ISSUE TITLE
Metadata link import ignores settings for Official Site and Gog Database

### ISSUE THREAD

**Issue by rogeriodomingos** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#79]
Links to Official Site and GOG Database are always added even when disabled in the add-on settings.

I suspect this is because the [PCGWGameController.AddLink](https://github.com/sharkusmanch/playnite-pcgamingwiki-metadata-provider/blob/fe45e46b549ef1470ac6d429a0f29b1daaaea265/src/PCGWGameController.cs#L287) method which does the filtering is not being used for those two links:
https://github.com/sharkusmanch/playnite-pcgamingwiki-metadata-provider/blob/fe45e46b549ef1470ac6d429a0f29b1daaaea265/src/PCGamingWikiHTMLParser.cs#L394-L404

**Comment by sharkusmanch** [comment]
Thanks for reporting, you're exactly right. Will be fixed in the next release.

**Comment by sharkusmanch** [comment]
Fixed in v1.2.5
