### ISSUE TITLE
Change DualShock 4 detection to PlayStation controller detection

### ISSUE THREAD

**Issue by lscholte** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#89]
It appears that PCGamingWiki changed how it handles PlayStation Controller support. It now labels it as PlayStation controllers instead of  DualShock 4 (which makes sense because people also use DualSense controllers). On a related note, it could be handy to check for adaptive trigger and haptive feedback support on each game as well.

Here's an example under controller types section: https://www.pcgamingwiki.com/wiki/Star_Wars_Jedi:_Survivor

NOTE: I will very likely take a stab at implementing this myself when I get the time as I have a particular interest in making sure this works as I have scripts that rely on accurate detection of PS controller support.

**Comment by sharkusmanch** [comment]
Thanks! Released with 1.3 - https://github.com/sharkusmanch/playnite-pcgamingwiki-metadata-provider/releases/tag/v1.3.0
